version: "3.11"

# Определение сервисов
services:
  # Сервис Traefik
  traefik:
    # Образ Docker
    image: traefik:3.0
    container_name: proxy-admin-panel
    # Отображение портов
    ports:
      # HTTP (80)
      - 80:80
      # HTTPS (443)
      - 443:443
    # Перезапуск сервиса
    restart: always
    # Метки для Traefik
    labels:
      # Включение Traefik для этого сервиса
      - traefik.enable=true
      # Подключение к сети traefik-public
      - traefik.docker.network=traefik-public
      # Порт панели управления Traefik
#      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      # Настройка маршрутизаторов
      # --- Панель управления Traefik
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)
#      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
#      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.${DOMAIN?Variable not set}`)
#      - traefik.http.routers.traefik-dashboard-https.tls=true
#      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
#      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      # --- Перенаправление HTTP на HTTPS
#      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
#      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
#      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
      # --- HTTP-аутентификация для панели управления
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
#      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
    # Тома для хранения данных
    volumes:
      # Сокет Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Сертификаты
      - traefik-public-certificates:/certificates
    # Команды для запуска Traefik
    command:
      # Включение Docker
      - --providers.docker
      # Обработка только явно отмеченных сервисов
      - --providers.docker.exposedbydefault=false
      # Точки входа (http и https)
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # Получение сертификатов Let's Encrypt
#      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
#      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
#      - --certificatesresolvers.le.acme.tlschallenge=true
      # Логи
      - --accesslog
      - --log
      # Включение панели управления
      - --api.dashboard=true
      - --api.insecure=true
    # Подключение к сети
    networks:
      # Сеть traefik-public
      - traefik-public

# Определение томов
volumes:
  # Том для сертификатов
  traefik-public-certificates:

# Определение сетей
networks:
  # Сеть traefik-public
  traefik-public:
    # Внешняя сеть
    external: true