version: "3.11"

services:
  db:
    container_name: main_database
    image: postgres:alpine3.19
    restart: always
    ports:
      - "5432:5432"
#    volumes:
#      - ./database:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
