services:
  db:
    container_name: main_database
    image: postgres:alpine3.19
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_app
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always
    networks:
      - default
  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    shm_size: 1gb
    depends_on:
      - selenium-hub
    restart: always
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - default

networks:
  default:
    driver: bridge