"""update

Revision ID: 627a2c64925e
Revises: 
Create Date: 2024-03-22 15:30:21.091486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "627a2c64925e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("is_video", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("link_img", sa.String(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_table(
        "process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iterate", sa.Integer(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("error", sa.Boolean(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("process")
    op.drop_table("links")
    # ### end Alembic commands ###
