"""Add Users

Revision ID: 964ccdaa09f0
Revises: 
Create Date: 2024-09-24 18:24:04.724143

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "964ccdaa09f0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("is_video", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("link_img", sa.String(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_table(
        "process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iterate", sa.Integer(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("error", sa.Boolean(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "settlement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("label_i", sa.String(length=255), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
        sa.UniqueConstraint("label_i"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_update_at"), "users", ["update_at"], unique=False)
    op.create_table(
        "accesstokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id", "token"),
    )
    op.create_index(
        op.f("ix_accesstokens_created_at"), "accesstokens", ["created_at"], unique=False
    )
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("label_i", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("settlement_types_id", sa.Integer(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_types_id"],
            ["settlement_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlements")
    op.drop_table("districts")
    op.drop_index(op.f("ix_accesstokens_created_at"), table_name="accesstokens")
    op.drop_table("accesstokens")
    op.drop_index(op.f("ix_users_update_at"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_table("settlement_types")
    op.drop_table("regions")
    op.drop_table("process")
    op.drop_table("links")
    # ### end Alembic commands ###
