"""Добавление таблиц локаций

Revision ID: 47ba09897e8a
Revises: 627a2c64925e
Create Date: 2024-04-15 14:07:40.271700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ba09897e8a"
down_revision: Union[str, None] = "627a2c64925e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "settlement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("label_i", sa.String(length=255), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
        sa.UniqueConstraint("label_i"),
    )
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("label_i", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("settlement_types_id", sa.Integer(), nullable=True),
        sa.Column("created_ad", sa.DateTime(), nullable=True),
        sa.Column("update_ad", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_types_id"],
            ["settlement_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlements")
    op.drop_table("districts")
    op.drop_table("settlement_types")
    op.drop_table("regions")
    # ### end Alembic commands ###
